#pragma once

#define GPIO_PORT_0 DT_NODELABEL(gpio0)
#define GPIO_PORT_1 DT_NODELABEL(gpio1)

#define EDGE_P0_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P1_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P2_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P3_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P4_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P5_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P7_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P8_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P9_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P10_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P11_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P12_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P13_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P14_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P15_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))
#define EDGE_P19_DEV DEVICE_DT_GET(DT_NODELABEL(gpio0))

#define EDGE_P6_DEV DEVICE_DT_GET(DT_NODELABEL(gpio1))
#define EDGE_P16_DEV DEVICE_DT_GET(DT_NODELABEL(gpio1))
#define EDGE_P20_DEV DEVICE_DT_GET(DT_NODELABEL(gpio1))

#define EDGE_P0_IDX 2
#define EDGE_P1_IDX 3
#define EDGE_P2_IDX 4
#define EDGE_P3_IDX 31
#define EDGE_P4_IDX 28
#define EDGE_P5_IDX 14
#define EDGE_P6_IDX 5
#define EDGE_P7_IDX 11
#define EDGE_P8_IDX 10
#define EDGE_P9_IDX 9
#define EDGE_P10_IDX 30
#define EDGE_P11_IDX 23
#define EDGE_P12_IDX 12
#define EDGE_P13_IDX 17
#define EDGE_P14_IDX 1
#define EDGE_P15_IDX 13
#define EDGE_P16_IDX 2
#define EDGE_P19_IDX 26
#define EDGE_P20_IDX 0

